title: "quartz-transformer-mmlabc"
description: "quartz-transformer-mmlabc"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/quartz-transformer-mmlabc
plugins:
  - jekyll-sitemap
